# Generated by Django 6.0.4 on 2026-05-05 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle'), ('CAR', 'Car')], default='MOTORCYCLE', max_length=20)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Rider Profiles',
            },
        ),
    ]
