# Generated by Django 6.0.4 on 2026-05-05 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='RiderTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('EARNING', 'Delivery Earning'), ('WITHDRAWAL', 'Cash Withdrawal'), ('BONUS', 'Bonus')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='riders.riderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
