# Generated by Django 6.0.4 on 2026-05-05 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_riderprofile_balance_ridertransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='service_capabilities',
            field=models.CharField(choices=[('DELIVERY', 'Delivery Only'), ('RIDE_HAILING', 'Ride-Hailing Only'), ('BOTH', 'Both Delivery & Ride-Hailing')], db_index=True, default='DELIVERY', max_length=20),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['is_online', 'is_available', 'service_capabilities'], name='riders_ride_is_onli_6dda04_idx'),
        ),
    ]
