# Generated by Django 6.0.4 on 2026-05-05 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_riderprofile_service_capabilities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='riderprofile',
            name='riders_ride_is_onli_6dda04_idx',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='can_do_delivery',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='can_do_ride_hailing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['is_online', 'is_available', 'can_do_delivery'], name='riders_ride_is_onli_5808b0_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['is_online', 'is_available', 'can_do_ride_hailing'], name='riders_ride_is_onli_8ffe2a_idx'),
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='service_capabilities',
        ),
    ]
