# Generated by Django 6.0.4 on 2026-05-10 21:03

from django.conf import settings
from django.db import migrations, models


if getattr(settings, "USE_POSTGIS", False):
    import django.contrib.gis.db.models.fields

    location_point_field = django.contrib.gis.db.models.fields.PointField(
        blank=True,
        geography=True,
        null=True,
        srid=4326,
    )
else:
    location_point_field = models.JSONField(null=True, blank=True)


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0005_riderprofile_location_wkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='location_point',
            field=location_point_field,
        ),
    ]
