# Generated by Django 6.0.4 on 2026-08-12 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_delivery_option"),
        ("riders", "0006_riderprofile_location_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiderOrderOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFFERED", "Offered"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OFFERED",
                        max_length=20,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("offered_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_offers",
                        to="orders.order",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_offers",
                        to="riders.riderprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-offered_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "status"],
                        name="riders_ride_order_i_130ae9_idx",
                    ),
                    models.Index(
                        fields=["rider", "status"],
                        name="riders_ride_rider_i_c702b1_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "status"],
                        name="riders_ride_expires_14c804_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACCEPTED")),
                        fields=("order",),
                        name="unique_accepted_rider_offer_per_order",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "OFFERED")),
                        fields=("order", "rider"),
                        name="unique_active_rider_offer_per_rider_order",
                    ),
                ],
            },
        ),
    ]
