# Generated by Django 6.0.4 on 2026-05-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
