# Generated by Django 6.0.4 on 2026-05-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_discount_amount_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('DELIVERY', 'Home Delivery'), ('PICKUP', 'Self-Pickup')], db_index=True, default='DELIVERY', max_length=20),
        ),
    ]
