# Generated by Django for multiple order prescription files.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_orderprescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderprescription",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="orders.order",
            ),
        ),
    ]
