@access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NDAwNzA0LCJpYXQiOjE3NzczOTg5MDQsImp0aSI6IjNhY2FhM2ZjZjZjNTQwYTU4ZGRhYjU1MTNlODc3Y2FiIiwidXNlcl9pZCI6IjgifQ.Kkbbh8137DQvhbdelWBZK1RowSbw3npaVHVMUcLDfmU
@category=2

POST http://127.0.0.1:8000/api/v1/jobs/postings/
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "category": {{category}},
  "title": "Coffee Maker - Matampay",
  "description": "Assist masons and carpenters in site preparation and daily tasks.",
  "requirements": "Physically fit, willing to work on-site, basic tool handling.",
  "location_text": "Matampay, Marawi City",
  "salary_min": 500,
  "salary_max": 800,
  "status": 1,
  "is_active": true
}
