@access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3Mzk5MTMwLCJpYXQiOjE3NzczOTczMzAsImp0aSI6IjlhYjEwZTU1ZTNkYTRkZTM4ZDJkZGJmODFjNzA4YzNlIiwidXNlcl9pZCI6IjcifQ.aJdosFhwWrStxKnUGEVmt1qWHdpqbSA65NDh2AgV2sw

POST http://127.0.0.1:8000/api/v1/users/profiles/
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "role": 1,
  "phone_number": "09170000022"
}
