@access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NDAxNDU1LCJpYXQiOjE3NzczOTk2NTUsImp0aSI6IjBlYTU3ZmY4MWE0ODRjYWE5ZDQzODM3YjNhOWQ2Njg5IiwidXNlcl9pZCI6IjgifQ._p4ix3Ut7V95QLM2sTln80MP2rNDnQZnOxGut6sFwm8
@applicationId=1

PATCH http://127.0.0.1:8000/api/v1/jobs/applications/{{applicationId}}/set_status/
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "status": 2
}
