# Generated by Django 6.0.4 on 2026-05-05 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('STRIPE', 'Stripe (Card/Digital)'), ('PAYMONGO', 'PayMongo (GCash/Maya/Card)'), ('WALLET', 'Internal Sarig Wallet')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending/Awaiting Payment'), ('AUTHORIZED', 'Authorized (Funds held, not captured)'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Payment Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('external_transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('provider_raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
