# Generated by Django 6.0.4 on 2026-05-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
