# Generated by Django 6.0.4 on 2026-05-05 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('dti_sec_certificate', models.FileField(upload_to='onboarding/merchants/dti_sec/')),
                ('mayors_permit', models.FileField(upload_to='onboarding/merchants/mayors_permit/')),
                ('bir_cor', models.FileField(blank=True, null=True, upload_to='onboarding/merchants/bir_cor/')),
                ('halal_certification', models.FileField(blank=True, null=True, upload_to='onboarding/merchants/halal/')),
                ('owner_valid_id', models.FileField(upload_to='onboarding/merchants/ids/')),
                ('storefront_photo', models.ImageField(upload_to='onboarding/merchants/photos/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Incomplete)'), ('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REQUEST_CHANGES', 'Changes Requested')], db_index=True, default='DRAFT', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant Application',
                'verbose_name_plural': 'Merchant Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle')], max_length=20)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('professional_drivers_license', models.FileField(upload_to='onboarding/riders/license/')),
                ('lto_or_cr', models.FileField(blank=True, null=True, upload_to='onboarding/riders/or_cr/')),
                ('nbi_clearance', models.FileField(upload_to='onboarding/riders/nbi/')),
                ('barangay_clearance', models.FileField(blank=True, null=True, upload_to='onboarding/riders/barangay/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Incomplete)'), ('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REQUEST_CHANGES', 'Changes Requested')], db_index=True, default='DRAFT', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Application',
                'verbose_name_plural': 'Rider Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
