# Generated by Django 6.0.4 on 2026-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantapplication",
            name="barangay",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="branch_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="business_type",
            field=models.CharField(
                choices=[("SHOP", "Shop"), ("RESTAURANT", "Restaurant")],
                default="RESTAURANT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="company_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="delivery_time",
            field=models.CharField(
                choices=[
                    ("MORNING", "Morning"),
                    ("AFTERNOON", "Afternoon"),
                    ("EVENING", "Evening"),
                    ("ALL_DAY", "All day"),
                ],
                default="ALL_DAY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="owner_first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="owner_last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="pinned_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="merchantapplication",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
