MARAWI_SERVICE_ZONES = [
    {
        "name": "Banggolo Poblacion",
        "slug": "banggolo-poblacion",
        "center_latitude": "8.000900",
        "center_longitude": "124.286700",
        "barangay_names": ["Banggolo Poblacion", "Banggolo"],
        "priority": 10,
    },
    {
        "name": "Basak Malutlut",
        "slug": "basak-malutlut",
        "center_latitude": "8.004500",
        "center_longitude": "124.299900",
        "barangay_names": ["Basak Malutlut", "Basak"],
        "priority": 20,
    },
    {
        "name": "Lilod Madaya",
        "slug": "lilod-madaya",
        "center_latitude": "8.000200",
        "center_longitude": "124.292600",
        "barangay_names": ["Lilod Madaya"],
        "priority": 30,
    },
    {
        "name": "Saduc",
        "slug": "saduc",
        "center_latitude": "8.012600",
        "center_longitude": "124.291200",
        "barangay_names": ["Saduc"],
        "priority": 40,
    },
    {
        "name": "Guimba",
        "slug": "guimba",
        "center_latitude": "8.011500",
        "center_longitude": "124.278500",
        "barangay_names": ["Guimba"],
        "priority": 50,
    },
    {
        "name": "Papandayan",
        "slug": "papandayan",
        "center_latitude": "7.997300",
        "center_longitude": "124.279900",
        "barangay_names": ["Papandayan"],
        "priority": 60,
    },
    {
        "name": "Matampay",
        "slug": "matampay",
        "center_latitude": "8.019200",
        "center_longitude": "124.287500",
        "barangay_names": ["Matampay"],
        "priority": 70,
    },
    {
        "name": "Rapasun MSU",
        "slug": "rapasun-msu",
        "center_latitude": "7.998000",
        "center_longitude": "124.256900",
        "barangay_names": ["Rapasun", "MSU", "Rapasun MSU"],
        "priority": 80,
    },
    {
        "name": "Marawi Poblacion",
        "slug": "marawi-poblacion",
        "center_latitude": "8.003400",
        "center_longitude": "124.283900",
        "barangay_names": ["Marawi Poblacion", "Poblacion"],
        "priority": 90,
    },
    {
        "name": "Lumbac Marinaut",
        "slug": "lumbac-marinaut",
        "center_latitude": "8.007600",
        "center_longitude": "124.272100",
        "barangay_names": ["Lumbac Marinaut", "Marinaut"],
        "priority": 100,
    },
    {
        "name": "Tuca Marinaut",
        "slug": "tuca-marinaut",
        "center_latitude": "8.009200",
        "center_longitude": "124.267400",
        "barangay_names": ["Tuca Marinaut"],
        "priority": 110,
    },
    {
        "name": "Sagonsongan",
        "slug": "sagonsongan",
        "center_latitude": "7.969800",
        "center_longitude": "124.295800",
        "barangay_names": ["Sagonsongan"],
        "priority": 120,
    },
    {
        "name": "Bubonga Lilod Madaya",
        "slug": "bubonga-lilod-madaya",
        "center_latitude": "8.002700",
        "center_longitude": "124.295500",
        "barangay_names": ["Bubonga Lilod Madaya"],
        "priority": 130,
    },
    {
        "name": "Raya Saduc",
        "slug": "raya-saduc",
        "center_latitude": "8.015900",
        "center_longitude": "124.294900",
        "barangay_names": ["Raya Saduc"],
        "priority": 140,
    },
]
