MARAWI_SERVICE_ZONES = [
    {
        "name": "Poblacion Core",
        "slug": "poblacion-core",
        "center_latitude": "8.002900",
        "center_longitude": "124.285500",
        "barangay_names": [
            "Banggolo Poblacion",
            "Dansalan",
            "Fort",
            "Lilod Madaya (Poblacion)",
            "Lumbaca Madaya (Poblacion)",
            "Marawi Poblacion",
            "Raya Madaya I",
            "Raya Madaya II",
            "South Madaya Proper",
            "Sangcay Dansalan",
            "Datu Sa Dansalan",
            "Mipaga Proper",
            "Norhaya Village",
        ],
        "priority": 10,
    },
    {
        "name": "Saduc Corridor",
        "slug": "saduc-corridor",
        "center_latitude": "8.013800",
        "center_longitude": "124.292800",
        "barangay_names": [
            "Saduc Proper",
            "Raya Saduc",
            "Panggao Saduc",
            "Lilod Saduc",
            "Sugod Proper",
            "Rorogagus East",
            "Rorogagus Proper",
            "Tampilong",
            "Pantaon (Langcaf)",
        ],
        "priority": 20,
    },
    {
        "name": "Matampay Calocan",
        "slug": "matampay-calocan",
        "center_latitude": "8.018700",
        "center_longitude": "124.288700",
        "barangay_names": [
            "Matampay",
            "Kormatan Matampay",
            "Calocan East",
            "Calocan West",
            "Wawalayan Calocan",
            "Gadongan",
            "Gadongan Mapantao",
            "Datu Saber (Navarro)",
            "Dimaluna",
            "Daguduban",
        ],
        "priority": 30,
    },
    {
        "name": "Marinaut MSU",
        "slug": "marinaut-msu",
        "center_latitude": "8.003900",
        "center_longitude": "124.268800",
        "barangay_names": [
            "Lumbac Marinaut",
            "Marinaut East",
            "Marinaut West",
            "Tuca Marinaut",
            "Wawalayan Marinaut",
            "Rapasun MSU",
            "Tuca",
            "Tongantongan-Tuca Timbangalan",
            "Timbangalan",
        ],
        "priority": 40,
    },
    {
        "name": "Basak Commercial",
        "slug": "basak-commercial",
        "center_latitude": "8.004700",
        "center_longitude": "124.299400",
        "barangay_names": [
            "Basak Malutlut",
            "East Basak",
            "Dayawan",
            "Bacolod Chico Proper",
            "Banga",
            "Bacong",
        ],
        "priority": 50,
    },
    {
        "name": "Ambolong Tuca",
        "slug": "ambolong-tuca",
        "center_latitude": "7.998700",
        "center_longitude": "124.287900",
        "barangay_names": [
            "Ambolong",
            "Boto Ambolong",
            "Olowa Ambolong",
            "Tuca Ambolong",
            "Toros",
            "Lumbaca Toros",
        ],
        "priority": 60,
    },
    {
        "name": "Bubonga Cadayonan",
        "slug": "bubonga-cadayonan",
        "center_latitude": "8.002500",
        "center_longitude": "124.295300",
        "barangay_names": [
            "Bubonga Pagalamatan",
            "Bubonga Lilod Madaya",
            "Bubonga Cadayonan",
            "Bubonga Marawi",
            "Bubonga Punod",
            "Cadayonan",
            "Cadayonan II",
            "Pagalamatan Gambai",
            "Pindolonan",
            "Paridi",
        ],
        "priority": 70,
    },
    {
        "name": "Sagonsongan Boganga",
        "slug": "sagonsongan-boganga",
        "center_latitude": "7.985700",
        "center_longitude": "124.292600",
        "barangay_names": [
            "Sagonsongan",
            "Boganga",
            "Boganga II",
            "Datu Dalidigan",
            "Datu Naga",
            "Emie Punud",
            "Sabala Manao",
            "Sabala Manao Proper",
        ],
        "priority": 80,
    },
    {
        "name": "Papandayan Guimba",
        "slug": "papandayan-guimba",
        "center_latitude": "8.006800",
        "center_longitude": "124.279000",
        "barangay_names": [
            "Papandayan",
            "Papandayan Caniogan",
            "Guimba (Lilod Proper)",
            "Somiorang",
            "Tolali",
            "Cabingan",
            "Kapantaran",
        ],
        "priority": 90,
    },
    {
        "name": "Bangon Moncado",
        "slug": "bangon-moncado",
        "center_latitude": "8.011000",
        "center_longitude": "124.277600",
        "barangay_names": [
            "Bangon",
            "Beyaba-Damag",
            "Moncado Colony",
            "Moncado Kadingilan",
            "Moriatao Loksadato",
            "Malimono",
            "Lomidong",
            "Poona Marantao",
            "Amito Marantao",
            "Pagayawan",
        ],
        "priority": 100,
    },
    {
        "name": "Dulay Kilala Patani",
        "slug": "dulay-kilala-patani",
        "center_latitude": "8.009500",
        "center_longitude": "124.281700",
        "barangay_names": [
            "Dulay Proper",
            "Dulay West",
            "Kilala",
            "Patani",
            "Sultan Corobong",
            "Sultan Panoroganan",
            "Angoyao",
            "Puga-an",
        ],
        "priority": 110,
    },
    {
        "name": "Outer East",
        "slug": "outer-east",
        "center_latitude": "8.006100",
        "center_longitude": "124.289900",
        "barangay_names": [
            "Bito Buadi Itowa",
            "Bito Buadi Parba",
            "Buadi Sacayo (Green)",
            "Bubong Lumbac",
            "Cabasaran",
        ],
        "priority": 120,
    },
]
