# Generated by Django 6.0.4 on 2026-05-04 21:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessVertical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business Vertical',
                'verbose_name_plural': 'Business Verticals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('is_open', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to=settings.AUTH_USER_MODEL)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='vendors.businessvertical')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city'], name='vendors_sto_city_49f9d2_idx'), models.Index(fields=['is_open'], name='vendors_sto_is_open_1bc166_idx'), models.Index(fields=['is_active'], name='vendors_sto_is_acti_86a00f_idx')],
            },
        ),
    ]
