# Generated by Django 6.0.4 on 2026-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_store_image_store_rating_alter_businessvertical_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='auto_accept_orders',
            field=models.BooleanField(default=False),
        ),
    ]
