# Generated by Django 6.0.4 on 2026-05-10 21:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_store_location_wkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
