# Generated by Django 6.0.4 on 2026-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0005_store_location_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="barangay",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="branch_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="store",
            name="company_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="store",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="store",
            name="delivery_time",
            field=models.CharField(
                choices=[
                    ("MORNING", "Morning"),
                    ("AFTERNOON", "Afternoon"),
                    ("EVENING", "Evening"),
                    ("ALL_DAY", "All day"),
                ],
                default="ALL_DAY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="pinned_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="store",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="store",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
