# Generated by Django 6.0.4 on 2026-07-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_stock_quantity_product_track_inventory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="dosage",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="generic_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="inventory_mode",
            field=models.CharField(
                choices=[("NONE", "None"), ("TRACKED", "Tracked")],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="medicine_form",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TABLET", "Tablet"),
                    ("CAPSULE", "Capsule"),
                    ("SYRUP", "Syrup"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="medicine_reference_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="preparation_time_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("FOOD", "Food"),
                    ("MEDICINE", "Medicine"),
                    ("GROCERY", "Grocery"),
                    ("GENERAL", "General"),
                ],
                default="FOOD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="requires_prescription",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("ITEM", "Item"),
                    ("SERVING", "Serving"),
                    ("PACK", "Pack"),
                    ("BOTTLE", "Bottle"),
                ],
                default="ITEM",
                max_length=20,
            ),
        ),
    ]
