# Generated by Django 6.0.4 on 2026-07-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_productreference"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productreference",
            new_name="catalog_pro_name_ce9885_idx",
            old_name="catalog_pro_name_69b43c_idx",
        ),
        migrations.RenameIndex(
            model_name="productreference",
            new_name="catalog_pro_brand_n_62d05d_idx",
            old_name="catalog_pro_brand_n_0ead5f_idx",
        ),
        migrations.RenameIndex(
            model_name="productreference",
            new_name="catalog_pro_barcode_ba6cd8_idx",
            old_name="catalog_pro_barcode_740c23_idx",
        ),
    ]
