# Generated by Django 6.0.4 on 2026-08-10 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0010_rename_catalog_pro_name_69b43c_idx_catalog_pro_name_ce9885_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="modifieritem",
            name="linked_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modifier_choice_links",
                to="catalog.product",
            ),
        ),
    ]
